# Use version 2
version: "2.0"

# My service collection
services:

    # Telephony asterisk
    asterisk:
        container_name: asterisk
        hostname: symbols
        restart: unless-stopped
        build: ./build/asterisk
        image: local/asterisk
        volumes:
            - "your_asterisk_conf.mine_path:/etc/asterisk/conf.mine"
        network_mode: host

    # Mednafen multiplay server
    mednafen:
        container_name: mednafen
        hostname: gamy
        restart: unless-stopped
        build: ./build/mednafen
        image: local/mednafen
        ports:
            - "4046:4046/tcp"

    # SSHD for reverse tunnels
    sshd:
        container_name: sshd
        hostname: essehodie
        restart: unless-stopped
        build:
            context: ./build/sshd
            args:
                - USER=your_user
                - PASSWORD=your_password
        image: local/sshd
        ports:
            - "2222:22/tcp"

    # Content delivery through HTTP
    content:
        container_name: content
        hostname: newspeak
        restart: unless-stopped
        build: /data/docker/web-server/content
        image: local/content
        volumes:
            - "your_ssl_path:/etc/ssl"
            - "your_content_path:/web"
        ports:
            - "443:443/tcp"

    # HTTP redirect
    redirect:
        container_name: redirect
        hostname: grandline
        restart: unless-stopped
        build: ./build/web-server/redirect
        image: local/redirect
        ports:
            - "80:80/tcp"

    audio-api:
        container_name: audio-api
        hostname: music
        restart: unless-stopped
        build: ./build/web-server/audio-server-api
        image: local/audio-api
        volumes:
            - "your_config_path/config.json:/web/config.json"
            - "your_data_path:/music"
            - "your_ssl_path:/etc/ssl"
        ports:
            - "444:444/tcp"

    # My audio frontend
    audio-application:
        container_name: audio-application
        hostname: frame
        restart: unless-stopped
        build: ./build/web-server/audio-server-application
        image: local/audio-applicaiton
        volumes:
            - "your_config_path/config.js:/web/config/config.js"
            - "your_ssl_path:/etc/ssl"
        ports:
                - "443:443/tcp"
