#!/bin/sh

# Initialize dbus
dbus-uuidgen > /var/lib/dbus/machine-id
mkdir -p /var/run/dbus
dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

# Initialize udev
RUNLEVEL="S" PREVLEVEL="N" /etc/init.d/udev start

# Initialize audio
pulseaudio -D --system

# User space

HOME="/steam"
startx

# Sleep

sleep infinity
